config/routes.rb
Rails.application.routes.draw do
  resources :cardpublicos
  resources :pedido_publicos
  devise_for :admins
  get 'control/index'

  resources :cars
  resources :pedidos
  resources :recomendacions
  resources :condicions
  resources :products
  get "inicio" => 'home#index'

  devise_for :users

   root 'control#index'
   get 'recomendaciones' => 'home#recomendaciones'
   get 'socios' => 'pedidos#socios'
   get 'aislados' => 'pedidos#aislados'
   get 'concentrados' => 'pedidos#concentrados'
   get 'complementos' => 'pedidos#complementos'
   get 'reglas' => 'home#condiciones'
   get 'email' => 'pedidos#email'
   post 'email' => 'cardpublicos#email'
   get 'shop' => 'pedido_publicos#advertencia'
   get 'tienda' => 'pedido_publicos#new'
   get 'carpublico' => 'cardpublicos#new'
   get 'gracias' => 'cardpublicos#gracias'
   post '/crear_producto', :to =>  'cars#crearcar'
   post '/crear_producto_publico', :to =>  'cardpublicos#crearcar'
   namespace :api do
    namespace :v1 do
      resources :productos, path: "productos"
      resources :productos_publicos, path: "productos_publicos"
    end
  end

end

app/models/cardpublico.rb
class Cardpublico < ActiveRecord::Base
end

app/controllers/cardpublicos_controller.rb
class CardpublicosController < ApplicationController
  before_action :set_cardpublico, only: [:show, :edit, :update, :destroy]

  # GET /cardpublicos
  # GET /cardpublicos.json
  def index
    @cardpublicos = Cardpublico.all
  end

  # GET /cardpublicos/1
  # GET /cardpublicos/1.json
  def show
  end

  def email
    @productos = Cardpublico.where(:pedidoID => params[:pedidoID])
    RestClient.post "https://api:key-e7d79c66e74391fdf48b657624f23ddc"\
    "@api.mailgun.net/v3/sandboxb9c2dadab0ea49f6b7130d1091646c59.mailgun.org/messages",
    :from => "Sistema de Pedidos <mailgun@sandboxb9c2dadab0ea49f6b7130d1091646c59.mailgun.org>",
    #:to => "krlos013@gmail.com",
    :to => "proteina@sinergroup.com.mx",
    :subject => "Solicitud de Pedido",
    :html => (render_to_string(template: "../views/cardpublicos/email")).to_str
    redirect_to "/gracias"
  end

  def gracias
    
  end
  # GET /cardpublicos/new
  def new
    @cardpublico = Cardpublico.new
    @productos = Product.all.pluck(:descripcion)
    @cardpublicos = Cardpublico.where(:pedidoID => params[:pedidoID])
  end

  # GET /cardpublicos/1/edit
  def edit
  end

  # POST /cardpublicos
  # POST /cardpublicos.json

  def crearcar
    @car = Cardpublico.new(:pedidoID => params[:pedidoID], :producto=> params[:producto], :cantidad=> params[:cantidad], :precio => (Product.select(:costo).where(:descripcion => params[:producto]).pluck(:costo).first) * (params[:cantidad].to_f))
     respond_to do |format|
      if @car.save
        # @consultore.update(:access => true)
        format.html { redirect_to :back, notice: 'User was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end
  def create
    @cardpublico = Cardpublico.new(cardpublico_params)
    #@precio = Product.where(:descripcion => params[:productos])
    #@cardpublico = Cardpublico.new(:pedidoID => params[:pedidoID], :producto=> params[:producto], :cantidad=> params[:cantidad], :precio=> @precio)
    respond_to do |format|
      if @cardpublico.save
        format.html { redirect_to :back, notice: 'Cardpublico was successfully created.' }
        format.json { render :show, status: :created, location: @cardpublico }
      else
        format.html { render :new }
        format.json { render json: @cardpublico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cardpublicos/1
  # PATCH/PUT /cardpublicos/1.json
  def update
    respond_to do |format|
      if @cardpublico.update(cardpublico_params)
        format.html { redirect_to :back, notice: 'Cardpublico was successfully updated.' }
        format.json { render :show, status: :ok, location: @cardpublico }
      else
        format.html { render :edit }
        format.json { render json: @cardpublico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cardpublicos/1
  # DELETE /cardpublicos/1.json
  def destroy
    @cardpublico.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Cardpublico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cardpublico
      @cardpublico = Cardpublico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cardpublico_params
      params.require(:cardpublico).permit(:pedidoID, :producto, :cantidad, :precio, :peso)
    end
end

app/helpers/cardpublicos_helper.rb
module CardpublicosHelper
end

app/views/cardpublicos/_form.html.erb
  <!-- Top Bar
================================================== -->
  <div id="topbar">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <ul class="topbar-contact">
            <li><i class="fa fa-phone-square"></i>01 (442) 2186601</li>
            <li><i class="fa fa-mobile"></i>442 275 5685 / 442 174 0218</li>
            <li>|</li>
            <li class="language dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-language"></i>Español <i class="fa fa-angle-down"></i></a>
              <ul class="dropdown-menu">
                <li><a href="#">English</a></li>
              </ul>
            </li>
          </ul>
          <!-- end .topbar-contact --> 
        </div>
        <!-- end .col-md-8 -->
        
         <div class="col-md-4">
          <ul class="social-icons pull-right">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
          </ul>
          <!-- end .social-icons --> 
          
        </div>
        <!-- end .col-md-4 --> 
      </div>
      <!-- end .row --> 
    </div>
    <!-- end .container --> 
  </div>
  <!-- end #topbar --> 
  <%= render "header" %>
  <div class="row">
  <div class="col-md-1 sidebar-line"></div>
  <div class="col-md-10 sidebar-line">
    <p>Cuentas Bancarias</p>
    <p><strong>BBVA Bancomer</strong></p>
    <p>Razón Social: SINERGROUP S DE RL</p>
    <p>No Cta. 0107787693</p>
    <p>Clave: 012680001077876933</p>
<%= form_tag :controller => 'cardpublicos', :action => 'crearcar', :method => 'post' do %>
  <div class="field">
    <%= hidden_field_tag :pedidoID, nil,:value => params[:pedidoID], :class=>"form-control" %>
  </div>
  <div class="field">
    <%= label_tag "Lista de Productos" %><br>
    <%= select_tag :producto, options_for_select(@productos), prompt: "Selecciona un producto de la lista", :class => "form-control tamano" %>
  </div>
  <div class="field">
    <%= label_tag :cantidad %><br>
    <%= text_field_tag :cantidad, nil,:class=>"form-control", :placeholder => "Captura la cantidad deseada", :required=>true %>
  </div>
  
  
  
  <div class="actions">
    <%= submit_tag "Agregar a carrito", :class => "btn btn-warning" %>
  </div>
  <% end %>

</div>
  <div class="col-md-1 sidebar-line"></div>
</div>

<div class="row">
<div class="col-md-1 sidebar-line"></div>
<div class="col-md-10 sidebar-line">
  <div class="table-responsive">
  <h1>Mi carrito</h1>
<strong><div id="total"></div></strong>
<table class="table table-middle">
  <thead>
    <tr>
      <th>Número de Pedido</th>
      <th>Producto</th>
      <th>Cantidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cardpublicos.each do |cardpublico| %>
      <tr>
        <td><%= cardpublico.pedidoID %></td>
        <td><%= cardpublico.producto %></td>
        <td><%= cardpublico.cantidad %></td>
        <td><%= link_to 'Eliminar Producto', cardpublico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<div class="col-md-1 sidebar-line"></div>
</div>
<div class="row">
<div class="col-md-1 sidebar-line"></div>
<div class="col-md-10 sidebar-line">
<%= form_tag :controller => 'cardpublicos', :action => 'email', :method => 'post' do %>
<%= hidden_field_tag :pedidoID,:nil, :class=> "form-control", :value => params[:pedidoID] %>
<div class="actions">
    <%= submit_tag "Solicitar pedido", :class => "btn btn-warning" %>
  </div>
  <% end %>
</div>
<div class="col-md-1 sidebar-line"></div>
</div>


<script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.13.3/react.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.13.3/JSXTransformer.js"></script>
<script src="https://rawgit.com/arqex/react-json/master/build/Json.js"></script>
<script src="//cdn.jsdelivr.net/refluxjs/0.2.11/reflux.min.js"></script>
<script type="text/jsx">

var url = "/api/v1/productos_publicos?pedido=<%= params[:pedidoID] %>" 
var Total = React.createClass({
           getInitialState: function() {
              return {
                data: ""
              };
            },
            componentDidMount: function() {
              var self = this;
              $.get(this.props.source, function(result) {
                var collection = result;
                if (this.isMounted()) {
                  this.setState({
                    data: collection
                  });
                }
              }.bind(this));
            },
            render: function() {   
              
              return (
                <span>
                 <h1>Total $ {this.state.data} + Envío $130 MXN </h1>   
                </span>
              );
            }
          });

         React.render(
        <Total source={url} />,
          document.getElementById('total')
     );

</script>

app/views/cardpublicos/_header.html.erb
<header id="header">
    <nav class="navbar yamm navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          <a class="navbar-brand" href="http://sinergroup.com.mx/">
            <%= image_tag("logo.png",:class=>"img-responsive") %>
            </a></div>
        <!-- end .navbar-header -->
        
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="http://sinergroup.com.mx/">Inicio</a></li>
           
          </ul>
          <!-- end .nav navbar-nav --> 
        </div>
        <!-- end .navbar-collapse collapse --> 
        
      </div>
      <!-- end .container --> 
    </nav>
    <!-- end .navbar --> 
    
  </header>

app/views/cardpublicos/edit.html.erb
<h1>Editing Cardpublico</h1>

<%= render 'form' %>

<%= link_to 'Show', @cardpublico %> |
<%= link_to 'Back', cardpublicos_path %>

app/views/cardpublicos/email.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="viewport" content="width=device-width" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Sinergroup</title>
<link href="styles.css" media="all" rel="stylesheet" type="text/css" />
</head>
<body itemscope itemtype="http://schema.org/EmailMessage">
<div>Tienes un nuevo pedido del socio <%= PedidoPublico.where(:id => params[:pedidoID]).pluck(:nombre).first %></div>
<table class="table table-middle">
	<thead>
		<tr>
			<th>Número de Pedido</th>
			<th>Productos</th>
			<th>Cantidad</th>
			<th>Precio por unidad</th>
			
		</tr>
	</thead>
	<tbody>
		<% @productos.each do |p| %>
		<tr>
			<td><%= p.pedidoID %></td>
			<td><%= p.producto %></td>
			<td><%= p.cantidad %></td>
			<td><%= Product.where(:descripcion => p.producto).pluck(:costo).first %></td>
			
		</tr>
		<% end %>
	</tbody>
</table>
<h5>Detalles del Pedido</h5>
<div>Nombre del cliente: <%= PedidoPublico.where(:id => params[:pedidoID]).pluck(:nombre).first %></div>
<div>Código Promocional: <%= PedidoPublico.where(:id => params[:pedidoID]).pluck(:codigopromocional).first %></div>
<div>Correo electrónico: <%= PedidoPublico.where(:id => params[:pedidoID]).pluck(:correo).first %></div>
<div>Télefono: <%= PedidoPublico.where(:id => params[:pedidoID]).pluck(:telefono).first %></div>
<h5>Detalles de envío</h5>
<div>Dirección de envío: <%= PedidoPublico.where(:id => params[:pedidoID]).pluck(:direccion).first %></div>
<div>Entre que Calles: <%= PedidoPublico.where(:id => params[:pedidoID]).pluck(:calles).first %></div>
<div>Municipio: <%= PedidoPublico.where(:id => params[:pedidoID]).pluck(:municipio).first %></div>
<div>Código Postal: <%= PedidoPublico.where(:id => params[:pedidoID]).pluck(:codigopostal).first %></div>

<h5>Datos de Facturación</h5>
<div>Código Postal: <%= PedidoPublico.where(:id => params[:pedidoID]).pluck(:rfc).first %></div>
<div>Razón Social: <%= PedidoPublico.where(:id => params[:pedidoID]).pluck(:razonsocial).first %></div>
<div>Dirección Fiscal: <%= PedidoPublico.where(:id => params[:pedidoID]).pluck(:direccionfiscal).first %></div>
<div>Municipio: <%= PedidoPublico.where(:id => params[:pedidoID]).pluck(:municipiofiscal).first %></div>
<div>Código Postal: <%= PedidoPublico.where(:id => params[:pedidoID]).pluck(:codigopostalfiscal).first %></div>
</body>
</html>

app/views/cardpublicos/gracias.html.erb
  <!-- Top Bar
================================================== -->
  <div id="topbar">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <ul class="topbar-contact">
            <li><i class="fa fa-phone-square"></i>01 (442) 2186601</li>
            <li><i class="fa fa-mobile"></i>442 275 5685 / 442 174 0218</li>
            <li>|</li>
            <li class="language dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-language"></i>Español <i class="fa fa-angle-down"></i></a>
              <ul class="dropdown-menu">
                <li><a href="#">English</a></li>
              </ul>
            </li>
          </ul>
          <!-- end .topbar-contact --> 
        </div>
        <!-- end .col-md-8 -->
        
         <div class="col-md-4">
          <ul class="social-icons pull-right">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
          </ul>
          <!-- end .social-icons --> 
          
        </div>
        <!-- end .col-md-4 --> 
      </div>
      <!-- end .row --> 
    </div>
    <!-- end .container --> 
  </div>
  <!-- end #topbar --> 
  <%= render "header" %>
   <div class="row">

      
      <div class="col-md-12">
        <h2 align="center">GRACIAS POR TU PEDIDO</h2>
  

        <div class="clearfix"></div>
        <div class="divider-singledotted"></div>
        <div class="mb-20"></div>
        <!-- end .mb-20 -->
       
        <h5 align="center">FAVOR DE REALIZAR EL DEPÓSITO CORRESPONDIENTE, A LA BREVEDAD NOS COMUNICAREMOS CONTIGO.</h5>
        <div class="divider-singledotted"></div>
        <div class="mb-20"></div>
        <!-- end .mb-20 --> 
        
      </div>
      <!-- end .col-md-6 -->



    </div>
</body>
</html>

app/views/cardpublicos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cardpublicos</h1>

<table>
  <thead>
    <tr>
      <th>Pedidoid</th>
      <th>Producto</th>
      <th>Cantidad</th>
      <th>Precio</th>
      <th>Peso</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cardpublicos.each do |cardpublico| %>
      <tr>
        <td><%= cardpublico.pedidoID %></td>
        <td><%= cardpublico.producto %></td>
        <td><%= cardpublico.cantidad %></td>
        <td><%= cardpublico.precio %></td>
        <td><%= cardpublico.peso %></td>
        <td><%= link_to 'Show', cardpublico %></td>
        <td><%= link_to 'Edit', edit_cardpublico_path(cardpublico) %></td>
        <td><%= link_to 'Destroy', cardpublico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cardpublico', new_cardpublico_path %>

app/views/cardpublicos/new.html.erb
<%= render 'form' %>

app/views/cardpublicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pedidoid:</strong>
  <%= @cardpublico.pedidoID %>
</p>

<p>
  <strong>Producto:</strong>
  <%= @cardpublico.producto %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @cardpublico.cantidad %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @cardpublico.precio %>
</p>

<p>
  <strong>Peso:</strong>
  <%= @cardpublico.peso %>
</p>

<%= link_to 'Edit', edit_cardpublico_path(@cardpublico) %> |
<%= link_to 'Back', cardpublicos_path %>