config/routes.rb
Rails.application.routes.draw do
  resources :cardpublicos
  resources :pedido_publicos
  devise_for :admins
  get 'control/index'

  resources :cars
  resources :pedidos
  resources :recomendacions
  resources :condicions
  resources :products
  get "inicio" => 'home#index'

  devise_for :users

   root 'control#index'
   get 'recomendaciones' => 'home#recomendaciones'
   get 'socios' => 'pedidos#socios'
   get 'aislados' => 'pedidos#aislados'
   get 'concentrados' => 'pedidos#concentrados'
   get 'complementos' => 'pedidos#complementos'
   get 'reglas' => 'home#condiciones'
   get 'email' => 'pedidos#email'
   post 'email' => 'cardpublicos#email'
   get 'shop' => 'pedido_publicos#advertencia'
   get 'tienda' => 'pedido_publicos#new'
   get 'carpublico' => 'cardpublicos#new'
   get 'gracias' => 'cardpublicos#gracias'
   post '/crear_producto', :to =>  'cars#crearcar'
   post '/crear_producto_publico', :to =>  'cardpublicos#crearcar'
   namespace :api do
    namespace :v1 do
      resources :productos, path: "productos"
      resources :productos_publicos, path: "productos_publicos"
    end
  end

end

app/models/recomendacion.rb
class Recomendacion < ActiveRecord::Base
end

app/controllers/recomendacions_controller.rb
class RecomendacionsController < ApplicationController
  before_action :set_recomendacion, only: [:show, :edit, :update, :destroy]

  # GET /recomendacions
  # GET /recomendacions.json
  def index
    @recomendacions = Recomendacion.all
  end

  # GET /recomendacions/1
  # GET /recomendacions/1.json
  def show
  end

  # GET /recomendacions/new
  def new
    @recomendacion = Recomendacion.new
  end

  # GET /recomendacions/1/edit
  def edit
  end

  # POST /recomendacions
  # POST /recomendacions.json
  def create
    @recomendacion = Recomendacion.new(recomendacion_params)

    respond_to do |format|
      if @recomendacion.save
        format.html { redirect_to "/", notice: 'Recomendacion was successfully created.' }
        format.json { render :show, status: :created, location: @recomendacion }
      else
        format.html { render :new }
        format.json { render json: @recomendacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recomendacions/1
  # PATCH/PUT /recomendacions/1.json
  def update
    respond_to do |format|
      if @recomendacion.update(recomendacion_params)
        format.html { redirect_to @recomendacion, notice: 'Recomendacion was successfully updated.' }
        format.json { render :show, status: :ok, location: @recomendacion }
      else
        format.html { render :edit }
        format.json { render json: @recomendacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recomendacions/1
  # DELETE /recomendacions/1.json
  def destroy
    @recomendacion.destroy
    respond_to do |format|
      format.html { redirect_to recomendacions_url, notice: 'Recomendacion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recomendacion
      @recomendacion = Recomendacion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recomendacion_params
      params.require(:recomendacion).permit(:userID, :leido)
    end
end

app/helpers/recomendacions_helper.rb
module RecomendacionsHelper
end

app/views/recomendacions/_form.html.erb
<%= form_for(@recomendacion) do |f| %>
  <% if @recomendacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recomendacion.errors.count, "error") %> prohibited this recomendacion from being saved:</h2>

      <ul>
      <% @recomendacion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userID %><br>
    <%= f.text_field :userID %>
  </div>
  <div class="field">
    <%= f.label :leido %><br>
    <%= f.text_field :leido %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recomendacions/edit.html.erb
<h1>Editing Recomendacion</h1>

<%= render 'form' %>

<%= link_to 'Show', @recomendacion %> |
<%= link_to 'Back', recomendacions_path %>

app/views/recomendacions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Recomendacions</h1>

<table>
  <thead>
    <tr>
      <th>Userid</th>
      <th>Leido</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recomendacions.each do |recomendacion| %>
      <tr>
        <td><%= recomendacion.userID %></td>
        <td><%= recomendacion.leido %></td>
        <td><%= link_to 'Show', recomendacion %></td>
        <td><%= link_to 'Edit', edit_recomendacion_path(recomendacion) %></td>
        <td><%= link_to 'Destroy', recomendacion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recomendacion', new_recomendacion_path %>

app/views/recomendacions/new.html.erb
<h1>New Recomendacion</h1>

<%= render 'form' %>

<%= link_to 'Back', recomendacions_path %>

app/views/recomendacions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Userid:</strong>
  <%= @recomendacion.userID %>
</p>

<p>
  <strong>Leido:</strong>
  <%= @recomendacion.leido %>
</p>

<%= link_to 'Edit', edit_recomendacion_path(@recomendacion) %> |
<%= link_to 'Back', recomendacions_path %>