config/routes.rb
Rails.application.routes.draw do
  resources :cardpublicos
  resources :pedido_publicos
  devise_for :admins
  get 'control/index'

  resources :cars
  resources :pedidos
  resources :recomendacions
  resources :condicions
  resources :products
  get "inicio" => 'home#index'

  devise_for :users

   root 'control#index'
   get 'recomendaciones' => 'home#recomendaciones'
   get 'socios' => 'pedidos#socios'
   get 'aislados' => 'pedidos#aislados'
   get 'concentrados' => 'pedidos#concentrados'
   get 'complementos' => 'pedidos#complementos'
   get 'reglas' => 'home#condiciones'
   get 'email' => 'pedidos#email'
   post 'email' => 'cardpublicos#email'
   get 'shop' => 'pedido_publicos#advertencia'
   get 'tienda' => 'pedido_publicos#new'
   get 'carpublico' => 'cardpublicos#new'
   get 'gracias' => 'cardpublicos#gracias'
   post '/crear_producto', :to =>  'cars#crearcar'
   post '/crear_producto_publico', :to =>  'cardpublicos#crearcar'
   namespace :api do
    namespace :v1 do
      resources :productos, path: "productos"
      resources :productos_publicos, path: "productos_publicos"
    end
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/car.rb
class Car < ActiveRecord::Base
end

app/models/cardpublico.rb
class Cardpublico < ActiveRecord::Base
end

app/models/condicion.rb
class Condicion < ActiveRecord::Base
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
end

app/models/pedido_publico.rb
class PedidoPublico < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/recomendacion.rb
class Recomendacion < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  def crearcar
      @car = Car.new(:pedidoID => params[:pedidoID], 
        :cantidad => params[:cantidad],
         :productoID => params[:productoID], 
         :costo => Product.where(:descripcion => params[:productoID]).pluck(:costo).first, :userID => params[:userID])
     respond_to do |format|
      if @car.save
        # @consultore.update(:access => true)
        format.html { redirect_to :back, notice: 'User was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
    
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:pedidoID, :cantidad, :productoID, :costo, :userID)
    end
end

app/controllers/control_controller.rb
class ControlController < ApplicationController
  def index
  	if admin_signed_in?
  		redirect_to "/products"
  	else
  		redirect_to "/inicio"
  	end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!
  def index
    @condicion = Condicion.new
  	@condiciones = Condicion.where(:userID => current_user.id).pluck(:leido).first
  	if @condiciones == "1" 
  		redirect_to "/pedidos"
  	else
  		redirect_to "/reglas"
  	end
  end
  def recomendaciones
    @recomendacion = Recomendacion.new
  	@recomendaciones = Recomendacion.where(:userID => current_user.id).pluck(:leido).first
  	if @recomendaciones == "1" 
  		redirect_to "/pedidos"
  	else
  		
  	end	
  end
  def condiciones
    @condicion = Condicion.new
  end
  
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: [:show, :edit, :update, :destroy]

  # GET /pedidos
  # GET /pedidos.json
  def index
    @pedidos = Pedido.where(:userID => current_user.id).order("id desc")
  end

  # GET /pedidos/1
  # GET /pedidos/1.json
  def show
  end
  def socios
  end
  def aislado
  end
  def concentrado
  end
  def complementos
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
  end

  # GET /pedidos/1/edit
  def edit
      @car = Car.new
      @cars = Car.where(:pedidoID => params[:id])
      @productos = Product.all.pluck(:descripcion)
  end

  # POST /pedidos
  # POST /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to '/', notice: 'Pedido was successfully created.' }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedidos/1
  # PATCH/PUT /pedidos/1.json
  def update
    @productos = Car.where(:pedidoID => params[:id])
    respond_to do |format| 
      if @pedido.update(pedido_params)
        
        format.html { redirect_to "/", notice: 'Pedido was successfully updated.' }
        format.json { render :show, status: :ok, location: @pedido }
        RestClient.post "https://api:key-e7d79c66e74391fdf48b657624f23ddc"\
    "@api.mailgun.net/v3/sandboxb9c2dadab0ea49f6b7130d1091646c59.mailgun.org/messages",
    :from => "Sistema de Pedidos <mailgun@sandboxb9c2dadab0ea49f6b7130d1091646c59.mailgun.org>",
    #:to => "proteina@sinergroup.com.mx",
    :to => "proteina@sinergroup.com.mx",
    :subject => "Solicitud de Pedido",
    :html => (render_to_string(template: "../views/pedidos/email")).to_str
      else
        format.html { render :edit }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1
  # DELETE /pedidos/1.json
  def destroy
    @pedido.destroy
    respond_to do |format|
      format.html { redirect_to "/", notice: 'Pedido was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def email

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pedido_params
      params.require(:pedido).permit(:titulo, :estatus, :comentarios, :envioC, :userID)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cardpublicos_helper.rb
module CardpublicosHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/condicions_helper.rb
module CondicionsHelper
end

app/helpers/control_helper.rb
module ControlHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pedido_publicos_helper.rb
module PedidoPublicosHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/recomendacions_helper.rb
module RecomendacionsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pedidoID %><br>
    <%= f.text_field :pedidoID %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.text_field :cantidad %>
  </div>
  <div class="field">
    <%= f.label :productoID %><br>
    <%= f.text_field :productoID %>
  </div>
  <div class="field">
    <%= f.label :costo %><br>
    <%= f.text_field :costo %>
  </div>
  <div class="field">
    <%= f.label :userID %><br>
    <%= f.text_field :userID %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cars</h1>

<table>
  <thead>
    <tr>
      <th>Pedidoid</th>
      <th>Cantidad</th>
      <th>Productoid</th>
      <th>Costo</th>
      <th>Userid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.pedidoID %></td>
        <td><%= car.cantidad %></td>
        <td><%= car.productoID %></td>
        <td><%= car.costo %></td>
        <td><%= car.userID %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pedidoid:</strong>
  <%= @car.pedidoID %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @car.cantidad %>
</p>

<p>
  <strong>Productoid:</strong>
  <%= @car.productoID %>
</p>

<p>
  <strong>Costo:</strong>
  <%= @car.costo %>
</p>

<p>
  <strong>Userid:</strong>
  <%= @car.userID %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/pedidos/_css.html.erb
<!-- CSS
================================================== -->
<link rel="stylesheet" href="/assets/bootstrap.self-c68c406b70db1115478355392ee8e55e46903052ef2acc9b83a09aa57ea2c0d1.css?body=1">
<link rel="stylesheet" href="/assets/plugins.self-fd9289bd3a8645ec18c55175d73e2bd2b70c8c0fb5dc151ac9260cee64628680.css?body=1" />

app/views/pedidos/_form.html.erb
  <!-- Top Bar
================================================== -->
  <div id="topbar">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <ul class="topbar-contact">
            <li><i class="fa fa-phone-square"></i>01 (442) 2186601</li>
            <li><i class="fa fa-mobile"></i>442 275 5685 / 442 174 0218</li>
            <li>|</li>
            <li class="language dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-language"></i>Español <i class="fa fa-angle-down"></i></a>
              <ul class="dropdown-menu">
                <li><a href="#">English</a></li>
              </ul>
            </li>
          </ul>
          <!-- end .topbar-contact --> 
        </div>
        <!-- end .col-md-8 -->
        
         <div class="col-md-4">
          <ul class="social-icons pull-right">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
          </ul>
          <!-- end .social-icons --> 
          
        </div>
        <!-- end .col-md-4 --> 
      </div>
      <!-- end .row --> 
    </div>
    <!-- end .container --> 
  </div>
  <!-- end #topbar --> 
<%= render "header" %>
<div class="row">
  <div class="col-md-1 sidebar-line"></div>
  <div class="col-md-10 sidebar-line">
  <h1>Nuevo Pedido</h1>
  <%= form_for(@pedido) do |f| %>
    <% if @pedido.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

        <ul>
        <% @pedido.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label "Escribe una breve descripción del pedido" %><br>
      <%= f.text_field :titulo, :class => "form-control" %>
    </div>
    <div class="field">
      <%= f.hidden_field :estatus, :value => "Pendiente" %>
    </div>
    <div class="field">
      <%= f.hidden_field :userID, :value => current_user.id %>
    </div>
    <div class="actions">
      <%= f.submit "Crear Pedido", :class=>"btn btn-success" %>
    </div>
  <% end %>
  </div>
  <div class="col-md-1 sidebar-line"></div>
</div>

app/views/pedidos/_form_edit.html.erb
  <!-- Top Bar
================================================== -->
  <div id="topbar">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <ul class="topbar-contact">
            <li><i class="fa fa-phone-square"></i>01 (442) 2186601</li>
            <li><i class="fa fa-mobile"></i>442 275 5685 / 442 174 0218</li>
            <li>|</li>
            <li class="language dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-language"></i>Español <i class="fa fa-angle-down"></i></a>
              <ul class="dropdown-menu">
                <li><a href="#">English</a></li>
              </ul>
            </li>
          </ul>
          <!-- end .topbar-contact --> 
        </div>
        <!-- end .col-md-8 -->
        
         <div class="col-md-4">
          <ul class="social-icons pull-right">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
          </ul>
          <!-- end .social-icons --> 
          
        </div>
        <!-- end .col-md-4 --> 
      </div>
      <!-- end .row --> 
    </div>
    <!-- end .container --> 
  </div>
  <!-- end #topbar --> 
<%= render "header" %>
<div class="row">
  <div class="col-md-1 sidebar-line"></div>
  <div class="col-md-10 sidebar-line">
<p>Cuentas Bancarias</p>
    <p><strong>BBVA Bancomer</strong></p>
    <p>Razón Social: SINERGROUP S DE RL</p>
    <p>No Cta. 0107787693</p>
    <p>Clave: 012680001077876933</p>

    
    <h1>Detalles del Pedido</h1>
<%= form_for(@pedido) do |f| %>
  <% if @pedido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

      <ul>
      <% @pedido.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if @cars.blank? %>
  
  <% else %>
  <div class="actions">
    <%= f.submit "Solicitar Pedido", :class=> "btn btn-success" %>
  </div>
  <div class="field">
    <%= f.label "Necesitas que algunos de tus productos sean mezclados" %>
    <%= f.text_field :comentarios, :placeholder => "Indicanos cuales ejem: Producto 1 10gr y Producto 2 500gr", :class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.select :envioC, options_for_select([["Enviar a cliente", "Enviar a cliente"], ["Enviar a socio", "Enviar a socio"]]), :required => true, prompt: "Selecciona un tipo de envío", :class => "form-control" %>
  </div>
  <% end %>
  <div class="field">
    <%= f.hidden_field :titulo %>
    <h3><%= @pedido.titulo %></h3>
  </div>
  <div class="field">
    <%= f.hidden_field :estatus, :value => "Enviado" %>
  </div>
  <div class="field">
    <%= f.hidden_field :userID, :value => current_user.id %>
  </div> 
<% end %>
</div>
<div class="col-md-1 sidebar-line"></div>
</div>
<div class="row">
  <div class="col-md-1 sidebar-line"></div>
  <div class="col-md-10 sidebar-line">
<%= form_tag :controller => 'cars', :action => 'crearcar', :method => 'post' do %>
  
  <div class="field">
    <%= hidden_field_tag :pedidoID, nil,:value => params[:id], :class=>"form-control" %>
  </div>
  <div class="field">
     <%= label_tag "Lista de Productos" %>
    <%= select_tag :productoID, options_for_select(@productos), prompt: "Selecciona un producto de la lista", :class => "form-control tamano" %>
  </div>
  <div class="field">
    <%= label_tag :cantidad %><br>
    <%= text_field_tag :cantidad, nil,:class=>"form-control", :required=>true, :placeholder => "Captura la cantidad deseada" %>
  </div>
  
  <div class="field">
    <%= hidden_field_tag :costo,:value=> Product.where(:descripcion => params[:id]).pluck(:costo), :class=>"form-control" %>
  </div>
  <div class="field">
    <%= hidden_field_tag :userID, nil,:class=>"form-control",:value=> current_user.id %>
  </div>
  <div class="actions">
    <%= submit_tag "Agregar a carrito", :class => "btn btn-warning" %>
  </div>
  <% end %>
</div>
<div class="col-md-1 sidebar-line"></div>
</div>

<div class="row">
<div class="col-md-1 sidebar-line"></div>
<div class="col-md-10 sidebar-line">
  <div class="table-responsive">
  <h1>Mi carrito</h1>
<strong><div id="total"></div></strong>
<table class="table table-middle">
  <thead>
    <tr>
      <th>Número de Pedido</th>
      <th>Cantidad</th>
      <th>Producto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.pedidoID %></td>
        <td><%= car.cantidad %></td>
        <td><%= car.productoID %></td>
      
        <td><%= link_to 'Eliminar Producto', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<div class="col-md-1 sidebar-line"></div>
</div>


<br>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.13.3/react.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.13.3/JSXTransformer.js"></script>
<script src="https://rawgit.com/arqex/react-json/master/build/Json.js"></script>
<script src="//cdn.jsdelivr.net/refluxjs/0.2.11/reflux.min.js"></script>
<script type="text/jsx">

var url = "/api/v1/productos?pedido=<%= params[:id] %>" 
var Total = React.createClass({
           getInitialState: function() {
              return {
                data: ""
              };
            },
            componentDidMount: function() {
              var self = this;
              $.get(this.props.source, function(result) {
                var collection = result;
                if (this.isMounted()) {
                  this.setState({
                    data: collection
                  });
                }
              }.bind(this));
            },
            render: function() {   
              
              return (
                <span>
                 <h1>Total $ {this.state.data}  </h1>   
                </span>
              );
            }
          });

         React.render(
        <Total source={url} />,
          document.getElementById('total')
     );

</script>

app/views/pedidos/_header.html.erb
<header id="header">
    <nav class="navbar yamm navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          <a class="navbar-brand" href="/">
            <%= image_tag("logo.png",:class=>"img-responsive") %>
            </a></div>
        <!-- end .navbar-header -->
        
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/socios">Socios</a></li>
            <li><a href="/aislados">Aislado</a></li>
            <li><a href="/concentrados">Concentrado</a></li>
            <li><a href="/complementos">Complementos</a></li>
            <li>
                <% if user_signed_in? %>
                <%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
              <% else %>
              <% end %>
            </li>
          </ul>
          <!-- end .nav navbar-nav --> 
        </div>
        <!-- end .navbar-collapse collapse --> 
        
      </div>
      <!-- end .container --> 
    </nav>
    <!-- end .navbar --> 
    
  </header>

app/views/pedidos/edit.html.erb
<%= render 'form_edit' %>

app/views/pedidos/email.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="viewport" content="width=device-width" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Sinergroup</title>
<link href="styles.css" media="all" rel="stylesheet" type="text/css" />
</head>
<body itemscope itemtype="http://schema.org/EmailMessage">
<div>Tienes un nuevo pedido del socio <%= current_user.id %> - <%= current_user.email %></div>
<table class="table table-middle">
	<thead>
		<tr>
			<th>Número de Pedido</th>
			<th>Productos</th>
			<th>Cantidad</th>
			<th>Precio por unidad</th>
			
		</tr>
	</thead>
	<tbody>
		<% @productos.each do |p| %>
		<tr>
			<td><%= p.pedidoID %></td>
			<td><%= p.productoID %></td>
			<td><%= p.cantidad %></td>
			<td><%= Product.where(:descripcion => p.productoID).pluck(:costo).first %></td>
			
		</tr>
		<% end %>
	</tbody>
</table>
<div>Comentarios: <%= Pedido.where(:id => params[:id]).pluck(:comentarios).first %></div>
<div>Tipo de Envio: <%= Pedido.where(:id => params[:id]).pluck(:envioC).first %></div>
</body>
</html>

app/views/pedidos/index.html.erb
<style type="text/css">
  .product-name {
    width: 30%!important;
  }
  .product-date {
    width: 50%!important;
  }
</style>
  <!-- Top Bar
================================================== -->
  <div id="topbar">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <ul class="topbar-contact">
            <li><i class="fa fa-phone-square"></i>01 (442) 2186601</li>
            <li><i class="fa fa-mobile"></i>442 275 5685 / 442 174 0218</li>
            <li>|</li>
            <li class="language dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-language"></i>Español <i class="fa fa-angle-down"></i></a>
              <ul class="dropdown-menu">
                <li><a href="#">English</a></li>
              </ul>
            </li>
          </ul>
          <!-- end .topbar-contact --> 
        </div>
        <!-- end .col-md-8 -->
        
         <div class="col-md-4">
          <ul class="social-icons pull-right">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
          </ul>
          <!-- end .social-icons --> 
          
        </div>
        <!-- end .col-md-4 --> 
      </div>
      <!-- end .row --> 
    </div>
    <!-- end .container --> 
  </div>
  <!-- end #topbar --> 
<%= render "header" %>
<div class="row">
      <div class="col-md-1 sidebar-line"></div>
      <div class="col-md-10 sidebar-line">
        <%= link_to 'Crear Pedido', new_pedido_path, :class=>"btn btn-theme" %>

        <div class="table-responsive">
          <table class="table table-middle">
            <thead>
              <tr>
                <th class="product-name">Número de Pedido</th>
                <th class="product-name">Pedido</th>
                <th class="product-price">Estatus</th>
                <th class="product-date">Fecha de Pedido</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
               <% @pedidos.each do |pedido| %>
                <tr class="alert fade in">
                  <td class="product-name"><h4><%= pedido.id %></h4>
                  </td>
                  <td class="product-name"><h5><%= pedido.titulo %></h5>
                  </td>
                  <td class="product-price"><%= pedido.estatus %></td>
                  <td class="product-price">
                    <%= pedido.created_at.strftime("%d/%m/%Y") %>
                  </td>
                  <% if pedido.estatus == "Enviado" %>
                 
                  <% else %>
                   <td><%= link_to 'Agregar Productos al pedido', edit_pedido_path(pedido), :class=>"btn btn-success" %></td>
                    <td><%= link_to 'Eliminar Pedido', pedido, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger" %></td>
                   <% end %>

                 
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <!-- end .table-responsive --> 
        <div class="clearfix mb-50"></div>
        <!-- end .mb-50 --> 
      </div>
      <div class="col-md-1 sidebar-line"></div>
</div>

app/views/pedidos/new.html.erb
<%= render 'form' %>

app/views/pedidos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cantidad:</strong>
  <%= @pedido.cantidad %>
</p>

<p>
  <strong>Producto:</strong>
  <%= @pedido.producto %>
</p>

<p>
  <strong>Userid:</strong>
  <%= @pedido.userID %>
</p>

<%= link_to 'Edit', edit_pedido_path(@pedido) %> |
<%= link_to 'Back', pedidos_path %>