config/routes.rb
Rails.application.routes.draw do
  resources :cardpublicos
  resources :pedido_publicos
  devise_for :admins
  get 'control/index'

  resources :cars
  resources :pedidos
  resources :recomendacions
  resources :condicions
  resources :products
  get "inicio" => 'home#index'

  devise_for :users

   root 'control#index'
   get 'recomendaciones' => 'home#recomendaciones'
   get 'socios' => 'pedidos#socios'
   get 'aislados' => 'pedidos#aislados'
   get 'concentrados' => 'pedidos#concentrados'
   get 'complementos' => 'pedidos#complementos'
   get 'reglas' => 'home#condiciones'
   get 'email' => 'pedidos#email'
   post 'email' => 'cardpublicos#email'
   get 'shop' => 'pedido_publicos#advertencia'
   get 'tienda' => 'pedido_publicos#new'
   get 'carpublico' => 'cardpublicos#new'
   get 'gracias' => 'cardpublicos#gracias'
   post '/crear_producto', :to =>  'cars#crearcar'
   post '/crear_producto_publico', :to =>  'cardpublicos#crearcar'
   namespace :api do
    namespace :v1 do
      resources :productos, path: "productos"
      resources :productos_publicos, path: "productos_publicos"
    end
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to "/", notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to "/", notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:codigo, :descripcion,:costo)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= render "header_admin" %>
<div class="row">
  <div class="col-md-1 sidebar-line"></div>
  <div class="col-md-10 sidebar-line">
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Código" %><br>
    <%= f.text_field :codigo, :class=> "form-control" , :required => true %>
  </div>
  <div class="field">
    <%= f.label "Descripción" %><br>
    <%= f.text_field :descripcion, :class=> "form-control", :required => true %>
  </div>
  <div class="field">
    <%= f.label :costo %><br>
    <%= f.text_field :costo , :class=> "form-control" , :required => true%>
  </div>
  <div class="actions">
    <%= f.submit "Guardar", :class=>"btn btn-success" %>
  </div>
<% end %>
</div>
<div class="col-md-1 sidebar-line"></div>
</div>

app/views/products/_header_admin.html.erb
  <!-- Top Bar
================================================== -->
  <div id="topbar">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <ul class="topbar-contact">
            <li><i class="fa fa-phone-square"></i>01 (442) 2186601</li>
            <li><i class="fa fa-mobile"></i>442 275 5685 / 442 174 0218</li>
            <li>|</li>
            <li class="language dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-language"></i>Español <i class="fa fa-angle-down"></i></a>
              <ul class="dropdown-menu">
                <li><a href="#">English</a></li>
              </ul>
            </li>
          </ul>
          <!-- end .topbar-contact --> 
        </div>
        <!-- end .col-md-8 -->
        
         <div class="col-md-4">
          <ul class="social-icons pull-right">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
          </ul>
          <!-- end .social-icons --> 
          
        </div>
        <!-- end .col-md-4 --> 
      </div>
      <!-- end .row --> 
    </div>
    <!-- end .container --> 
  </div>
  <!-- end #topbar --> 

<header id="header">
    <nav class="navbar yamm navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          <a class="navbar-brand" href="/">
            <%= image_tag("logo.png",:class=>"img-responsive") %>
            </a></div>
        <!-- end .navbar-header -->
        
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li>
              <a href="/users/sign_up">Registrar Usuarios</a>
            </li>
            <li>
                <% if admin_signed_in? %>
                <%= link_to "Cerrar sesion", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
              <% else %>
              <% end %>
            </li>
          </ul>
          <!-- end .nav navbar-nav --> 
        </div>
        <!-- end .navbar-collapse collapse --> 
        
      </div>
      <!-- end .container --> 
    </nav>
    <!-- end .navbar --> 
</header>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%= render "header_admin" %>
<div class="row">
  <div class="col-md-1 sidebar-line"></div>
  <div class="col-md-10 sidebar-line">
<h1>Catálogo de Productos</h1>
<div class="table-responsive">
  <table class="table table-middle">
  <thead>
    <tr>
      <th>Código</th>
      <th>Descripción</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.codigo %></td>
        <td><%= product.descripcion %></td>
        <td><%= product.costo %></td>
        <td><%= link_to 'Editar', edit_product_path(product) %></td>
        <td><%= link_to 'Eliminar', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'Agregar producto', new_product_path %>

</div>
<div class="col-md-1 sidebar-line"></div>
</div>

app/views/products/new.html.erb
<%= render 'form' %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @product.codigo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @product.descripcion %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>